### ISSUE TITLE
一个纯浏览器的方式？

### ISSUE THREAD

**Issue by ldXiao** [banana-space/tikz2svg#2]
现有wasm版本的pdftex https://github.com/SwiftLaTeX/SwiftLaTeX, 支持tikz/tikz-cd
再用比如 https://github.com/dawbarton/pdf2svg 做一个wasm， 不强制矢量图的话应该有现成nodejs包

假如走得通就可移除服务器端对TeX的依赖

1.减轻server负载
2.简化部署
3.方便btex输出静态模式，这里静态指的是比如可以部署在github page上

**Comment by abccsss** [comment]
网页 demo 里说：

> Run merely 2X slower than native binaries.

因此至少在香蕉空间网站上，暂时不考虑换成这个浏览器版。
